### ISSUE TITLE
Elpi eval and inference rules in STLC

### ISSUE THREAD

**Issue by krpcannon** [shaolintl/fstar-type-checker#3]
As mentioned, the ELPI paper introduces two inference rules for type-checking a program generated by the STLC: one corresponding typing application and another for typing an abstraction as a function.

They are written in the paper as follows:

of (app M N) B :- of M (arr A B), of N A.
of (lam F) (arr A B) :- pi x\ of x A => of (F x) B.

In the paper they also mention the the goal (of (lam (w\ app w w)) T) should succeed. There must be a misunderstanding on my part, then, because 1) this goal does not succeed when I test it and 2) it is not true that it will succeed _IF_ the following accurately describes proof-search:

of (lam (w\ app w w)) T.
F = (w\ app w w)
T = arr A B
New goal: (of (app c c) B), add clause (of c A)  --as mentioned in paper

However, (of (app c c) B) cannot (?) succeed because we cannot prove (of c (arr A B)). In fact, we know c is of type A.

To test my thinking, I changed the first rule to: 

of (app M N) B :- of M (arr A B)**; of M A**, of N A. 

And now it succeeds, and unifies T =arr  (arr X0 X1) X1 and arr X2 X1 (first result doesn't really make sense).

**Comment by shaolintl** [comment]
I could not find they claim that
of (lam (w\ app w w)) T.
can be type checked. In fact, it is impossible to (finitely) type app x x for any x since the types of each argument must be different.

If you change the example to 
of (lam (w\ app w a)) T.
and add a clause
of a _.
you should get success. Please tell me if you dont.

Your change succeeds since you require now that only 
of c A, of c A succeed where you added previously the assumption
of c A

**Comment by krpcannon** [comment]
Yes, I supposed it would not be possible, so I am relieved to hear that I simply misread the paper and that there wasn't some deep misunderstanding. 

Apparently that example was referencing their call-by-name evaluation
